version: '3'

services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/duducp/Redis:/var/lib/postgresql/data