export enum CacheEnum {
  CLIENTS = 'CLIENTS',
  CLIENTS_SELECT = 'CLIENTS_SELECT',
  LOCALS = 'LOCALS',
  LOCALS_SELECT = 'LOCALS_SELECT',
  PEOPLES = 'PEOPLES',
  PEOPLES_SELECT = 'PEOPLES_SELECT',
}
